name: github pages deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Install Go
        run: |
          sudo apt-get remove golang-go
          sudo apt-get remove --auto-remove golang-go
          sudo rm -rf /usr/local/go
          sudo rm -rf /usr/local/go1.12
          sudo rm -rf /usr/local/go1.27
          sudo apt-get update
          wget https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
          sudo tar -xvf go1.14.4.linux-amd64.tar.gz
          sudo chown -R root:root ./go
          sudo cp -r go /usr/local
          sudo cp -r go /usr/local/go1.12
          sudo cp -r go /usr/local/go1.27
          sudo ln -sf /usr/local/go/bin/go /usr/bin/go
          sudo echo 'GOROOT=/usr/local/go' >> ~/.profile
          sudo echo 'GOPATH=$HOME/work' >>~/.profile
          sudo echo 'PATH=$GOROOT/bin:$GOPATH/bin' >>~/.profile
          source ~/.profile

      - name: Debug
        run: |
          pwd
          go env
          which go
          go version

      - name: Install deps-ga
        run: |
          sudo make deps-ga

      - name: Build
        run: |
          sudo chown -R root:root $GITHUB_WORKSPACE
          sudo make build

      - uses: ipfs-shipyard/ipfs-github-action@v1
        with:
          path_to_add: $GITHUB_WORKSPACE/build/website
          cluster_host: /dnsaddr/cluster.ipfs.io
          cluster_user: ${{ secrets.CLUSTER_USER }}
          cluster_password: ${{ secrets.CLUSTER_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy using SSH
        env:
          DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo chown -R runner $GITHUB_WORKSPACE
          sudo chown -R runner .git/
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --local user.email "no-reply-spec-deploy@protocol.ai"
          git config --local user.name "no-reply-spec-deploy"

          bin/publish-to-gh-pages.sh
