name: CI 

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      
      - run: npm install
      - run: npm run build

      # Pin the built site to ipfs-cluster, output the cid as `steps.ipfs.outputs.cid`
      # see: https://github.com/ipfs-shipyard/ipfs-github-action
      - uses: hugomrdias/ipfs-github-action@debug-pin
        id: ipfs
        with:
          path_to_add: public
          cluster_host: /dnsaddr/cluster.ipfs.io
          cluster_user: ${{ secrets.CLUSTER_USER }}
          cluster_password: ${{ secrets.CLUSTER_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo /ipfs/${{ steps.ipfs.outputs.cid }}

      - run: echo ${{ github.ref }}

      # This branch updates a dnslink for a domain if the current branch should be deployed to prod.
      # see https://github.com/ipfs-shipyard/js-dnslink-dnsimple
      - run: npx dnslink-dnsimple --domain beta.spec.filecoin.io --link /ipfs/${{ steps.ipfs.outputs.cid }}
        env:
          DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
        # TODO: change to master once merged.
        if: github.ref == 'refs/heads/beta'
