name: CI 

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      
      # get lotus deps...
      - run: sudo apt install bzr

      - run: npm install
      - run: npm test
      - run: npm run build

      # Pin the built site to ipfs-cluster, output the cid as `steps.ipfs.outputs.cid`
      # see: https://github.com/ipfs-shipyard/ipfs-github-action
      - uses: ipfs-shipyard/ipfs-github-action@v2.0.0
        if: github.event.pull_request.head.repo.full_name == github.repository
        id: ipfs
        with:
          path_to_add: public
          cluster_host: /dnsaddr/cluster.ipfs.io
          cluster_user: ${{ secrets.CLUSTER_USER }}
          cluster_password: ${{ secrets.CLUSTER_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo /ipfs/${{ steps.ipfs.outputs.cid }}

      # Update the dnslink if changes to the current branch should go live
      # see https://github.com/ipfs-shipyard/js-dnslink-dnsimple
      - run: npx dnslink-dnsimple --domain spec.filecoin.io --link /ipfs/${{ steps.ipfs.outputs.cid }}
        if: github.ref == 'refs/heads/master' && github.event.pull_request.head.repo.full_name == github.repository
        env:
          DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
